added cursor modes as https://github.com/ziglibs/ansi-term/issues/15
ziglibs/ansi-term pull request #17
Opened 2023-03-21 14:17 UTC by ZanovelloAlberto

2023-03-22 13:05 UTC, joachimschmidt557 requested changes
Thank you! This is a pretty non-intrusive change, so I'm open to accepting this PR when some small style changes are applied.

2023-03-22 13:05 UTC, joachimschmidt557 commented on src/cursor.zig
> +    BLINKING_BLOCK = 1,
The Zig naming convention is that enum values should be camel case, so e.g. `blinking_block`. You can make an exception for the `I` beam (e.g. `blinking_I_beam`).

2023-03-22 14:21 UTC, ZanovelloAlberto commented
it is my first pull request im trying to figure it out who it works, im not sure which button i have to press, anyway i have pushed another commit in my fork

2023-03-25 21:32 UTC, joachimschmidt557 commented
Yes, pushing commits to the branch connected with this PR will update this PR too. Looks good to me, thanks!

2023-03-25 21:32 UTC, merged